baseball:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CH_HOST') }}"
      port: 8123
      user: "{{ env_var('CH_USER') }}"
      password: "{{ env_var('CH_PASSWORD') }}"
      schema: staging
      secure: false